# Generated by Django 3.1 on 2022-05-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
                ('locationId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.location')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('password', models.CharField(max_length=64)),
                ('changedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='locationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.location'),
        ),
    ]
