# Generated by Django 3.1 on 2022-05-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('kilometrage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('checkDate', models.DateField()),
                ('nextCheckDate', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='PartsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
                ('conditionMeasurment', models.CharField(choices=[('KM', 'Kilometres'), ('MI', 'Miles'), ('Time', 'Time'), ('L', 'Volume')], default='KM', max_length=5)),
                ('stockCondition', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, null=True)),
                ('manufacterDate', models.DateField(null=True)),
                ('currentCondition', models.FloatField()),
                ('additionalInfo', models.JSONField(null=True)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partstype')),
            ],
        ),
    ]
