# Generated by Django 3.1 on 2022-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220524_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engineVol',
            field=models.FloatField(default=1.5),
        ),
    ]
